---
title: "ANOVA"
author: "Christof Seiler"
date: "Stanford University, Spring 2016, STATS 205"
output:
  beamer_presentation:
    incremental: no
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
set.seed(1234)
```

## Overview

Before:

* One-Sample, Two-Sample Problems (one or two populations)

Today:

* ANOVA (three or more populations)

## What is ANOVA?

* Classical ANOVA for balanced data does three things at once:

1. As exploratory data analysis, an ANOVA is an organization of an additive data decomposition, and its sums of squares indicate the variance of each component of the decomposition (or, equivalently, each set of terms of a linear model)
2. Comparisons of mean squares, along with F-tests [or F-like tests; see, e.g., Cornfield and Tukey (1956)], allow testing of a nested sequence of models
3. Closely related to the ANOVA is a linear model fit with coefficient estimates and standard errors

## One-Way ANOVA

* Determine the effect of a single factor $A$ on a response over a specific population
* Assume $A$ consists of $k$ levels or treatmens
* In a completely randomize design, $n$ subjects are randomly selected from the reference population
* $n_j$ randomly assigned to level $i = 1,\dots,k$
* Let $j$th be the response in the $i$th level denoted by $Y_{ij}$, $j = 1,\dots,n$
* Assumptions:
    * Responses are independent of another
    * Distribution among levels differ by at most shifts in location

## One-Way ANOVA

* The full model is
$$Y_{ij} = \mu_i + e_{ij}, \hspace{0.5cm} j=1,\dots,n, \hspace{0.5cm} i = 1,\dots,k$$
with 
    * iid random errors $e_{ij}$ with density $f(x)$ and distribution $F(x)$
    * $\mu_i$ location parameter of $i$th level (for us this will be the median)
* Data
$$
\begin{tabular}{cccc}
\hline
\multicolumn{4}{c}{Treatment} \\
1 & 2 & \dots & k \\
\hline
$Y_{11}$ & $Y_{12}$ & $\dots$ & $Y_{1k}$ \\
$Y_{21}$ & $Y_{22}$ & \dots & $Y_{2k}$ \\
\vdots & \vdots &       & \vdots \\
$Y_{j1}$ & $Y_{j2}$ & \dots & $Y_{jk}$ 
\end{tabular}
$$

## One-Way ANOVA

* The parameters of interest are 
$$\delta_{ii'} = \mu_{i'} - \mu_i, \hspace{0.5cm} i \ne i', \hspace{0.5cm} i = 1,\dots,k$$
* The usual statistical analysis is the hypothesis test
$$H_0: \mu_1 = \cdots = \mu_k \hspace{0.5cm} \text{versus} \hspace{0.5cm} H_A: \mu_i \ne \mu_{i'}$$
* Followed by pairwise confidence intervals $\delta_{ii'}$

## Kruskal–Wallis Test

* TODO
