---
title: "Multivariate Rank Tests"
author: "Christof Seiler"
date: "Stanford University, Spring 2016, Stats 205"
output:
  beamer_presentation:
    incremental: no
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
set.seed(1234)
```

## Overview

* So far, we have seen only univariate nonparametric tests
* Today, we'll cover multivariate generaliztion
1. Two-Sample tests
    * Graph-based: Friedman and Rafsky test
    * Data depth-based: Tukey depth
2. Associations
    * Mantel test

# Two-Sample Tests

## Wald-Wolfowitz Runs Test

* Is another univariate tests
* Example: Hot hand in basketball

## Friedman and Rafsky Test

* Generalization of Wald-Wolfowitz runs test to higher dimensions
* Uses minimal spanning trees

## Minimal Spanning Trees

TODO

## Tukey Depth

* It is based on **depth functions**
* One example is the Tukey depth

# Associations

## Mantel Test

* Test for multivariate assocations
* Or associations between matrices

## References

* Bhattacharya (2015). Power of Graph-Based Two-Sample Tests
* Tukey (1974). Mathematics and the Picturing of Data
* Holmes (1997). Lecture Notes on [Computer Intensive Methods in Statistics](http://statweb.stanford.edu/~susan/courses/b494/node3.html#SECTION00390000000000000000)
