---
title: "Two-Sample Problems"
author: "Christof Seiler"
date: "Stanford University, Spring 2016, STATS 205"
output:
  ioslides_presentation: 
    smaller: yes
    transition: faster
    widescreen: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Last Lecture

* We revisited the bootstrap
* We learned how to use Monte Carlo simulations 
* We learned how to enumerate all possible outcomes
* We saw an examples evaluating correlations between LSAT and GPS in law school

## Today

We will learn how to treat two-sample problems using 

* rank-based methods, 
* permutation tests, 
* and the boostrap

# Autism Brain Imaging Data

## Data

Modern application where we encouter two sample problems very frequently. 

### Neuroimaging

* Compare two populations, such as people who are autistic and healthy controls
* Find morphological, connectivity, and functional difference 
* Inform new therapies and cures

### Running Example for this Lecture

Our running example will directly work on preprocessed neuroimaging data from the Autism Brain Imaging Data Exchange (ABIDE). 
The data is openly avaialbe on the ABIDE website [here](http://preprocessed-connectomes-project.org/abide/)).

ABIDE is a collaboration of 16 international imaging sites that have aggregated and are openly sharing neuroimaging data from 539 individuals suffering from ASD and 573 typical controls. For now will only use a subset of their data to speedup our analysis and foucs on 40 paricipants.

# Overall Conclusion

## Summary

TODO

* ... 

## Next Lecture

We will learn about nonparametrics for regression.

## Homeworks

Homework 3 will be posted on the course website today.

Deadline: Tuesday, April 20th before class at 1:30 pm.
